### ISSUE TITLE
 unresolved externals

### ISSUE THREAD

**Issue by ghost** [nirai-compiler/src#10]
Hi. I'm trying to use Nirai, but I'm having trouble linking when I compile the cxx file. It keeps spewing "unresolved external symbol". I have compiled Panda3D, ran postbuild, ran aespyd with the VS2010 command prompt, and cmade python with VS2013, cmake gui version 3.5.0-rc2, and only now, it is failing. Here's the output:

`Compiling CXX codes...
aes.cxx
rebuilt.cxx
main.cxx
Linking...
   Creating library built/rebuilt.lib and object built/rebuilt.exp
main.obj : error LNK2001: unresolved external symbol _init_direct
main.obj : error LNK2001: unresolved external symbol _init_core
pythonembed.lib(tokenizer.obj) : error LNK2001: unresolved external symbol ___report_rangecheckfailure
pythonembed.lib(marshal.obj) : error LNK2001: unresolved external symbol ___report_rangecheckfailure
pythonembed.lib(getpath.obj) : error LNK2001: unresolved external symbol ___report_rangecheckfailure
pythonembed.lib(posixmodule.obj) : error LNK2001: unresolved external symbol ___report_rangecheckfailure
pythonembed.lib(unicodedata.obj) : error LNK2001: unresolved external symbol ___report_rangecheckfailure
pythonembed.lib(typeobject.obj) : error LNK2001: unresolved external symbol ___report_rangecheckfailure
pythonembed.lib(traceback.obj) : error LNK2001: unresolved external symbol ___report_rangecheckfailure
pythonembed.lib(longobject.obj) : error LNK2001: unresolved external symbol ___report_rangecheckfailure
pythonembed.lib(floatobject.obj) : error LNK2001: unresolved external symbol ___report_rangecheckfailure
pythonembed.lib(_math.obj) : error LNK2001: unresolved external symbol __libm_sse2_log_precise
pythonembed.lib(longobject.obj) : error LNK2001: unresolved external symbol __libm_sse2_log_precise
pythonembed.lib(complexobject.obj) : error LNK2001: unresolved external symbol __libm_sse2_log_precise
pythonembed.lib(cmathmodule.obj) : error LNK2001: unresolved external symbol __libm_sse2_log_precise
pythonembed.lib(mathmodule.obj) : error LNK2001: unresolved external symbol __libm_sse2_log_precise
pythonembed.lib(floatobject.obj) : error LNK2001: unresolved external symbol __imp__round
pythonembed.lib(mathmodule.obj) : error LNK2001: unresolved external symbol __imp__round
pythonembed.lib(floatobject.obj) : error LNK2001: unresolved external symbol __dtoui3
pythonembed.lib(dtoa.obj) : error LNK2001: unresolved external symbol __dtoui3
pythonembed.lib(audioop.obj) : error LNK2001: unresolved external symbol __dtoui3
pythonembed.lib(timemodule.obj) : error LNK2001: unresolved external symbol __dtoui3
pythonembed.lib(floatobject.obj) : error LNK2001: unresolved external symbol __libm_sse2_pow_precise
pythonembed.lib(complexobject.obj) : error LNK2001: unresolved external symbol __libm_sse2_pow_precise
pythonembed.lib(mathmodule.obj) : error LNK2001: unresolved external symbol __libm_sse2_pow_precise
pythonembed.lib(complexobject.obj) : error LNK2001: unresolved external symbol __libm_sse2_cos_precise
pythonembed.lib(cmathmodule.obj) : error LNK2001: unresolved external symbol __libm_sse2_cos_precise
pythonembed.lib(mathmodule.obj) : error LNK2001: unresolved external symbol __libm_sse2_cos_precise
pythonembed.lib(complexobject.obj) : error LNK2001: unresolved external symbol __libm_sse2_exp_precise
pythonembed.lib(cmathmodule.obj) : error LNK2001: unresolved external symbol __libm_sse2_exp_precise
pythonembed.lib(mathmodule.obj) : error LNK2001: unresolved external symbol __libm_sse2_exp_precise
pythonembed.lib(_math.obj) : error LNK2001: unresolved external symbol __libm_sse2_exp_precise
pythonembed.lib(complexobject.obj) : error LNK2001: unresolved external symbol __libm_sse2_sin_precise
pythonembed.lib(cmathmodule.obj) : error LNK2001: unresolved external symbol __libm_sse2_sin_precise
pythonembed.lib(mathmodule.obj) : error LNK2001: unresolved external symbol __libm_sse2_sin_precise
pythonembed.lib(_lsprof.obj) : error LNK2001: unresolved external symbol __ltod3
pythonembed.lib(posixmodule.obj) : error LNK2001: unresolved external symbol __ltod3
pythonembed.lib(timemodule.obj) : error LNK2001: unresolved external symbol __ltod3
pythonembed.lib(xxsubtype.obj) : error LNK2001: unresolved external symbol __ltod3
pythonembed.lib(datetimemodule.obj) : error LNK2001: unresolved external symbol __ltod3
pythonembed.lib(audioop.obj) : error LNK2001: unresolved external symbol __libm_sse2_sqrt_precise
pythonembed.lib(cmathmodule.obj) : error LNK2001: unresolved external symbol __libm_sse2_sqrt_precise
pythonembed.lib(_math.obj) : error LNK2001: unresolved external symbol __libm_sse2_sqrt_precise
pythonembed.lib(cmathmodule.obj) : error LNK2001: unresolved external symbol __libm_sse2_tan_precise
pythonembed.lib(mathmodule.obj) : error LNK2001: unresolved external symbol __libm_sse2_log10_precise
pythonembed.lib(timemodule.obj) : error LNK2001: unresolved external symbol __dtol3
pythonembed.lib(_lsprof.obj) : error LNK2001: unresolved external symbol __dtol3
built/rebuilt.exe : fatal error LNK1120: 15 unresolved externals
The following command returned non-zero value (1120): link /LTCG /LTCG:STATUS /nologo /out:built/rebuilt.exe "built/aes.obj" "built/main.obj" "built/rebui...`
I hope you can help me!

**Comment by loblao** [comment]
Please use VS2010 for all operations.

**Comment by ghost** [comment]
I tried, but it said something about (i cant remember exactly) vcxproj needing a later version. I'll try again when I have access to the computer that has the build on it.

**Comment by ghost** [comment]
I can't\* use VS2010. I can generate it with VS2010, but I can't open it, because:
'C:\Rebuiltsrc\build\pythoncmade\ALL_BUILD.vcxproj' cannot be opened because its project type (.vcxproj) is not supported by this version of the application.

To open it, please use a version that supports this type of project.
**edit: *i don't think I installed c++ stuff when I installed visual studio. I'm reinstalling VS2010 now, making sure to select c++ stuff**

**Comment by ghost** [comment]
Down to 2 unresolved externals now, about core and direct.
`main.obj : error LNK2001: unresolved external symbol _init_direct
main.obj : error LNK2001: unresolved external symbol _init_core`
Any fix for this?

**Comment by loblao** [comment]
Is your local clone up to date? Those were fixed in `d9ec58c77bfbb6a30fe5d13c041b24846522efef`

**Comment by ghost** [comment]
No, I'll update it now. Thanks for informing me.

**Comment by ghost** [comment]
My problem is fixed. Thank you for your help, loblao. You're a genius.
