### ISSUE TITLE
Assertion Error

### ISSUE THREAD

**Issue by LanceBladestorme** [nirai-compiler/src#16]
I'm trying to use the Nirai folder found in Toontown Stride's src to compile my Toontown server for my friends (so they don't have to deal with so many folders). When running make.py in VS 2010 command prompt, I keep running into this error. I'm little confused what it means by run with -OO.

```
C:\Private Server\ToontownStride-master\build>python make.py
Traceback (most recent call last):
  File "make.py", line 9, in <module>
    from niraitools import *
  File "nirai/src\niraitools.py", line 1, in <module>
    assert not **debug** # Run with -OO
AssertionError
```

**Comment by AskAlice** [comment]
@LanceBladestorme can you elaborate on how you fixed it?

**Comment by mfwass** [comment]
The error is self explanatory... _"Run with -OO"_.

Let me help you out there:
`python -OO make.py`
