### ISSUE TITLE
Fatal Error

### ISSUE THREAD

**Issue by LanceBladestorme** [nirai-compiler/src#17]
Figured out silly mistake I made earlier, but I ran into this error while compiling my toontown server. By any chance are you aware of what's causing this fatal error?

C:\Private Server\ToontownStride-master\build>python -OO make.py -cnm
Compiling CXX codes...
main.cxx
aes.cxx
stride.cxx
Linking...
LINK : fatal error LNK1181: cannot open input file 'pythonembed.lib'
The following command returned non-zero value (1181): link /LTCG /LTCG:STATUS /nologo /out:built/stride.exe "built/aes.obj" "built/main.obj" "built/stride...

**Comment by LanceBladestorme** [comment]
closest thing I have to pythonembed.lib is pythonembed.vcxproj, pythonembed.vcxproj.filters, and pythonembed.sln

**Comment by LanceBladestorme** [comment]
Looking over the Cmake file, I realize for whatever reason CMake did not make the pythonembed.lib file. Trying a few different methods to get it to install.

**Comment by LanceBladestorme** [comment]
Having no luck getting the pythonembed.lib file to form. Anyone else experience or a similar problem or know how to fix this?

**Comment by xseano** [comment]
@LanceBladestorme Would you mind explaining how you came up with a fix for this, if any?

**Comment by linktlh** [comment]
Cmake only generates the project, use VS2010 to build it.
