### ISSUE TITLE
Error while building python

### ISSUE THREAD

**Issue by Nickdoge** [nirai-compiler/src#19]
Hello, I was building the python included with Nirai and i have this issue. Im using visual studio 14 2015

Build FAILED.

"C:\Users\Nicolas\Desktop\Nirai\python\build\ALL_BUILD.vcxproj" (default target
) (1) ->
"C:\Users\Nicolas\Desktop\Nirai\python\build\pythonembed.vcxproj" (default targ
et) (3) ->
(ClCompile target) ->
  C:\Users\Nicolas\Desktop\Nirai\python\Modules\timemodule.c(713): error C2065:
 'timezone': undeclared identifier [C:\Users\Nicolas\Desktop\Nirai\python\build
\pythonembed.vcxproj]
  C:\Users\Nicolas\Desktop\Nirai\python\Modules\timemodule.c(721): error C2065:
 'timezone': undeclared identifier [C:\Users\Nicolas\Desktop\Nirai\python\build
\pythonembed.vcxproj]
  C:\Users\Nicolas\Desktop\Nirai\python\Modules\timemodule.c(724): error C2065:
 'daylight': undeclared identifier [C:\Users\Nicolas\Desktop\Nirai\python\build
\pythonembed.vcxproj]
  C:\Users\Nicolas\Desktop\Nirai\python\Modules\timemodule.c(726): error C2065:
 'tzname': undeclared identifier [C:\Users\Nicolas\Desktop\Nirai\python\build\p
ythonembed.vcxproj]
  C:\Users\Nicolas\Desktop\Nirai\python\Modules\timemodule.c(726): error C2109:
 subscript requires array or pointer type [C:\Users\Nicolas\Desktop\Nirai\pytho
n\build\pythonembed.vcxproj]

**Comment by CodeAnGo** [comment]
>  Im using visual studio 14 2015

There's your issue, Nirai Python can only be built using VS2010 (Moreso the Visual Studio Command Prompt (2010))

**Comment by Nickdoge** [comment]
Alright, It built. Thanks for the help.
