### ISSUE TITLE
The cursor and icon

### ISSUE THREAD

**Issue by Weirdodude101** [nirai-compiler/src#23]
I understand it may not seem like a Nirai issue, but, when I test the client decompiled before I compile it with Nirai everything with the icon and cursor works fine. As I set all of the config files up correctly, I dont seem to know what would go wrong in the compiling of the client that doesn't allow them to work compiled.

**Comment by mfwass** [comment]
See #22.  This is an application-level issue and we cannot help you with it.  Check your resources and make sure you're _actually_ loading the file from the **correct location**.
