### ISSUE TITLE
Segmentation Fault 11

### ISSUE THREAD

**Issue by ghost** [nirai-compiler/src#27]
I don't know much about this type of error. I think it has something to do with memory or something allocated by the OS being exceeded. Is there any way I can stop this? The segfault occurs when loading DNA files with libpandadna, so the issue might actually be with libpandadna but I don't know.

**Comment by mfwass** [comment]
Get a backtrace with gdb and send that here.

**Comment by ghost** [comment]
I don't know if this is helpful or not. I ran gdb and did the following commands: `target exec ./rebuilt` `run` `backtrace` in that order.

Here's what the backtrace command told me:
```
#0  0x0000000100645c10 in ?? ()
#1  0x0000000107773ff8 in ?? ()
#2  0x0000000107773f20 in ?? ()
#3  0x000000010390a110 in ?? ()
#4  0x0000000101d95460 in ?? ()
#5  0x00007fff5fbeff68 in ?? ()
#6  0x00000001077736d0 in ?? ()
#7  0x00007fff5fbefce0 in ?? ()
#8  0x0000000100648962 in ?? ()
#9  0x0000000000000000 in ?? ()
```

I'm also thinking this issue is to do with Nirai rather than libpandadna. Should I close the issue on the libpandadna page?

**Comment by mfwass** [comment]
See https://github.com/loblao/libpandadna/issues/58#issuecomment-310853229
