### ISSUE TITLE
NIRAI SECURITY BREACHED

### ISSUE THREAD

**Issue by RegDogg** [nirai-compiler/src#29]
Nirai Is not as secure as one might think, therefore I do not recommend using f Nirai without any form of sophisticated obfuscation. You can easily dump the decrypted GameData.nri via a debugger after searching through the binary via a tool like Ghidra. So be very precise when using Nirai, I know it is old and no longer maintained, so if you use this, still be aware that the game you compile always has a chance to be reverse engineered.

**Comment by loblao** [comment]
This has been known for a while. In fact, Nirai has been deprecated for years. I'm going to archive the repositories.

Use [Pypperoni](https://github.com/Pypperoni) for better (albeit not perfect) resistance against reverse engineering.
