### ISSUE TITLE
building for mac does not work!

### ISSUE THREAD

**Issue by DarthMDev** [nirai-compiler/src#4]
Undefined symbols for architecture x86_64:
  "_CRYPTO_THREADID_set_callback", referenced from:
      __setup_ssl_threads in libpythonembed.a(_ssl.c.o)
  "_CRYPTO_THREADID_set_numeric", referenced from:
      __ssl_threadid_callback in libpythonembed.a(_ssl.c.o)
  "_HMAC_CTX_copy", referenced from:
      _PKCS5_PBKDF2_HMAC_fast in libpythonembed.a(_hashopenssl.c.o)
  "_SSL_CTX_set_next_proto_select_cb", referenced from:
      __set_npn_protocols in libpythonembed.a(_ssl.c.o)
  "_SSL_CTX_set_next_protos_advertised_cb", referenced from:
      __set_npn_protocols in libpythonembed.a(_ssl.c.o)
  "_SSL_get0_next_proto_negotiated", referenced from:
      _PySSL_selected_npn_protocol in libpythonembed.a(_ssl.c.o)
  "_SSL_select_next_proto", referenced from:
      __selectNPN_cb in libpythonembed.a(_ssl.c.o)
  "_TLSv1_1_method", referenced from:
      _context_new in libpythonembed.a(_ssl.c.o)
  "_TLSv1_2_method", referenced from:
      _context_new in libpythonembed.a(_ssl.c.o)
  "init_libmovies()", referenced from:
      _main in main.o
  "init_libpandadna()", referenced from:
      niraicall_onLoadGameData() in empire.o
  "init_libOpenALAudio()", referenced from:
      load_openal() in main.o
      __GLOBAL__sub_I_main.cxx in main.o
  "init_libcocoadisplay()", referenced from:
      _main in main.o
  "init_libpnmimagetypes()", referenced from:
      _main in main.o
  "Create_OpenALAudioManager()", referenced from:
      load_openal() in main.o
      __GLOBAL__sub_I_main.cxx in main.o
  "TypedObject::~TypedObject()", referenced from:
      niraicall_onLoadGameData() in empire.o
  "AudioManager::register_AudioManager_creator(AudioManager\* (_)())", referenced from:
      load_openal() in main.o
      __GLOBAL__sub_I_main.cxx in main.o
  "DatagramIterator::get_string()", referenced from:
      niraicall_onLoadGameData() in empire.o
  "DatagramIterator::extract_bytes(unsigned long)", referenced from:
      niraicall_onLoadGameData() in empire.o
  "Notify::assert_failure(char const_, int, char const_)", referenced from:
      niraicall_onLoadGameData() in empire.o
  "Notify::ptr()", referenced from:
      niraicall_onLoadGameData() in empire.o
  "Datagram::append_data(void const_, unsigned long)", referenced from:
      niraicall_onLoadGameData() in empire.o
  "Datagram::~Datagram()", referenced from:
      niraicall_onLoadGameData() in empire.o
  "vtable for Datagram", referenced from:
      niraicall_onLoadGameData() in empire.o
  NOTE: a missing vtable usually means the first non-inline virtual member function has no definition.
  "_init_core", referenced from:
      _main in main.o
  "_init_direct", referenced from:
      _main in main.o
  "_init_subprocess", referenced from:
      __PyImport_Inittab in libpythonembed.a(config.c.o)
  "_initegg", referenced from:
      _main in main.o
  "_initfx", referenced from:
      _main in main.o
  "_initinterrogatedb", referenced from:
      _main in main.o
  "_initlibpandadna", referenced from:
      niraicall_onLoadGameData() in empire.o
  "_initnt", referenced from:
      __PyImport_Inittab in libpythonembed.a(config.c.o)
  "_initode", referenced from:
      _main in main.o
  "_initphysics", referenced from:
      _main in main.o
  "_uchar_type_handle", referenced from:
      niraicall_onLoadGameData() in empire.o
ld: symbol(s) not found for architecture x86_64

**Comment by mfwass** [comment]
this is not a Nirai error, I do not have a fix for you.

**Comment by DarthMDev** [comment]
Damn it
