### ISSUE TITLE
building on windows doesnt work

### ISSUE THREAD

**Issue by DarthMDev** [nirai-compiler/src#5]
aes.cxx
Linking...
pythonembed.lib(import.obj) : error LNK2005: _PyImport_GetModuleDict already defined in libp3pystub.lib(p3pystub_pystub.obj)
pythonembed.lib(sysmodule.obj) : error LNK2005: _PySys_GetObject already defined in libp3pystub.lib(p3pystub_pystub.obj)
pythonembed.lib(pythonrun.obj) : error LNK2005: _Py_IsInitialized already defined in libp3pystub.lib(p3pystub_pystub.obj)
pythonembed.lib(pythonrun.obj) : error LNK2005: _Py_Initialize already defined in libp3pystub.lib(p3pystub_pystub.obj)
pythonembed.lib(pythonrun.obj) : error LNK2005: _PyErr_Print already defined in libp3pystub.lib(p3pystub_pystub.obj)
pythonembed.lib(typeobject.obj) : error LNK2005: _PyType_GenericAlloc already defined in libp3pystub.lib(p3pystub_pystub.obj)
pythonembed.lib(typeobject.obj) : error LNK2005: _PyType_IsSubtype already defined in libp3pystub.lib(p3pystub_pystub.obj)
pythonembed.lib(typeobject.obj) : error LNK2005: _PyType_Ready already defined in libp3pystub.lib(p3pystub_pystub.obj)
pythonembed.lib(obmalloc.obj) : error LNK2005: _PyObject_Free already defined in libp3pystub.lib(p3pystub_pystub.obj)
pythonembed.lib(obmalloc.obj) : error LNK2005: __PyObject_DebugFree already defined in libp3pystub.lib(p3pystub_pystub.obj)
pythonembed.lib(dictobject.obj) : error LNK2005: _PyDict_Type already defined in libp3pystub.lib(p3pystub_pystub.obj)
pythonembed.lib(dictobject.obj) : error LNK2005: _PyDict_New already defined in libp3pystub.lib(p3pystub_pystub.obj)
pythonembed.lib(dictobject.obj) : error LNK2005: _PyDict_GetItem already defined in libp3pystub.lib(p3pystub_pystub.obj)
pythonembed.lib(dictobject.obj) : error LNK2005: _PyDict_SetItem already defined in libp3pystub.lib(p3pystub_pystub.obj)
pythonembed.lib(dictobject.obj) : error LNK2005: _PyDict_DelItem already defined in libp3pystub.lib(p3pystub_pystub.obj)
pythonembed.lib(dictobject.obj) : error LNK2005: _PyDict_Size already defined in libp3pystub.lib(p3pystub_pystub.obj)
pythonembed.lib(dictobject.obj) : error LNK2005: _PyDict_GetItemString already defined in libp3pystub.lib(p3pystub_pystub.obj)
pythonembed.lib(dictobject.obj) : error LNK2005: _PyDict_SetItemString already defined in libp3pystub.lib(p3pystub_pystub.obj)
pythonembed.lib(dictobject.obj) : error LNK2005: _PyDict_DelItemString already defined in libp3pystub.lib(p3pystub_pystub.obj)
pythonembed.lib(exceptions.obj) : error LNK2005: _PyExc_Exception already defined in libp3pystub.lib(p3pystub_pystub.obj)
pythonembed.lib(exceptions.obj) : error LNK2005: _PyExc_StandardError already defined in libp3pystub.lib(p3pystub_pystub.obj)
pythonembed.lib(exceptions.obj) : error LNK2005: _PyExc_TypeError already defined in libp3pystub.lib(p3pystub_pystub.obj)
pythonembed.lib(exceptions.obj) : error LNK2005: _PyExc_StopIteration already defined in libp3pystub.lib(p3pystub_pystub.obj)
pythonembed.lib(exceptions.obj) : error LNK2005: _PyExc_SystemExit already defined in libp3pystub.lib(p3pystub_pystub.obj)
pythonembed.lib(exceptions.obj) : error LNK2005: _PyExc_RuntimeError already defined in libp3pystub.lib(p3pystub_pystub.obj)
pythonembed.lib(exceptions.obj) : error LNK2005: _PyExc_AttributeError already defined in libp3pystub.lib(p3pystub_pystub.obj)
pythonembed.lib(exceptions.obj) : error LNK2005: _PyExc_IndexError already defined in libp3pystub.lib(p3pystub_pystub.obj)
pythonembed.lib(exceptions.obj) : error LNK2005: _PyExc_ValueError already defined in libp3pystub.lib(p3pystub_pystub.obj)
pythonembed.lib(exceptions.obj) : error LNK2005: _PyExc_AssertionError already defined in libp3pystub.lib(p3pystub_pystub.obj)
pythonembed.lib(exceptions.obj) : error LNK2005: _PyExc_BufferError already defined in libp3pystub.lib(p3pystub_pystub.obj)
pythonembed.lib(exceptions.obj) : error LNK2005: _PyExc_FutureWarning already defined in libp3pystub.lib(p3pystub_pystub.obj)
pythonembed.lib(ceval.obj) : error LNK2005: _PyEval_InitThreads already defined in libp3pystub.lib(p3pystub_pystub.obj)
pythonembed.lib(ceval.obj) : error LNK2005: _PyEval_SaveThread already defined in libp3pystub.lib(p3pystub_pystub.obj)
pythonembed.lib(ceval.obj) : error LNK2005: _PyEval_RestoreThread already defined in libp3pystub.lib(p3pystub_pystub.obj)
pythonembed.lib(ceval.obj) : error LNK2005: _PyEval_CallObjectWithKeywords already defined in libp3pystub.lib(p3pystub_pystub.obj)
pythonembed.lib(listobject.obj) : error LNK2005: _PyList_Type already defined in libp3pystub.lib(p3pystub_pystub.obj)
pythonembed.lib(listobject.obj) : error LNK2005: _PyList_New already defined in libp3pystub.lib(p3pystub_pystub.obj)
pythonembed.lib(listobject.obj) : error LNK2005: _PyList_GetItem already defined in libp3pystub.lib(p3pystub_pystub.obj)
pythonembed.lib(listobject.obj) : error LNK2005: _PyList_SetItem already defined in libp3pystub.lib(p3pystub_pystub.obj)
pythonembed.lib(listobject.obj) : error LNK2005: _PyList_Append already defined in libp3pystub.lib(p3pystub_pystub.obj)
pythonembed.lib(listobject.obj) : error LNK2005: _PyList_AsTuple already defined in libp3pystub.lib(p3pystub_pystub.obj)
pythonembed.lib(unicodeobject.obj) : error LNK2005: _PyUnicode_Type already defined in libp3pystub.lib(p3pystub_pystub.obj)
pythonembed.lib(unicodeobject.obj) : error LNK2005: _PyUnicodeUCS2_FromStringAndSize already defined in libp3pystub.lib(p3pystub_pystub.obj)
pythonembed.lib(unicodeobject.obj) : error LNK2005: _PyUnicodeUCS2_FromWideChar already defined in libp3pystub.lib(p3pystub_pystub.obj)
pythonembed.lib(unicodeobject.obj) : error LNK2005: _PyUnicodeUCS2_AsWideChar already defined in libp3pystub.lib(p3pystub_pystub.obj)
pythonembed.lib(unicodeobject.obj) : error LNK2005: _PyUnicodeUCS2_GetSize already defined in libp3pystub.lib(p3pystub_pystub.obj)
pythonembed.lib(object.obj) : error LNK2005: __Py_NoneStruct already defined in libp3pystub.lib(p3pystub_pystub.obj)
pythonembed.lib(object.obj) : error LNK2005: __Py_NotImplementedStruct already defined in libp3pystub.lib(p3pystub_pystub.obj)
pythonembed.lib(object.obj) : error LNK2005: __Py_NegativeRefcount already defined in libp3pystub.lib(p3pystub_pystub.obj)
pythonembed.lib(object.obj) : error LNK2005: __PyObject_Del already defined in libp3pystub.lib(p3pystub_pystub.obj)
pythonembed.lib(object.obj) : error LNK2005: _PyObject_Repr already defined in libp3pystub.lib(p3pystub_pystub.obj)
pythonembed.lib(object.obj) : error LNK2005: _PyObject_Str already defined in libp3pystub.lib(p3pystub_pystub.obj)
pythonembed.lib(object.obj) : error LNK2005: _PyObject_Compare already defined in libp3pystub.lib(p3pystub_pystub.obj)
pythonembed.lib(object.obj) : error LNK2005: _PyObject_RichCompareBool already defined in libp3pystub.lib(p3pystub_pystub.obj)
pythonembed.lib(object.obj) : error LNK2005: _PyObject_GetAttrString already defined in libp3pystub.lib(p3pystub_pystub.obj)
pythonembed.lib(object.obj) : error LNK2005: _PyObject_HasAttrString already defined in libp3pystub.lib(p3pystub_pystub.obj)
pythonembed.lib(object.obj) : error LNK2005: _PyObject_SetAttrString already defined in libp3pystub.lib(p3pystub_pystub.obj)
pythonembed.lib(object.obj) : error LNK2005: _PyObject_GenericGetAttr already defined in libp3pystub.lib(p3pystub_pystub.obj)
pythonembed.lib(object.obj) : error LNK2005: _PyObject_GenericSetAttr already defined in libp3pystub.lib(p3pystub_pystub.obj)
pythonembed.lib(object.obj) : error LNK2005: _PyObject_IsTrue already defined in libp3pystub.lib(p3pystub_pystub.obj)
pythonembed.lib(object.obj) : error LNK2005: _PyCallable_Check already defined in libp3pystub.lib(p3pystub_pystub.obj)
pythonembed.lib(object.obj) : error LNK2005: __Py_Dealloc already defined in libp3pystub.lib(p3pystub_pystub.obj)
pythonembed.lib(object.obj) : error LNK2005: _PyMem_Free already defined in libp3pystub.lib(p3pystub_pystub.obj)
pythonembed.lib(stringobject.obj) : error LNK2005: _PyString_Type already defined in libp3pystub.lib(p3pystub_pystub.obj)
pythonembed.lib(stringobject.obj) : error LNK2005: _PyString_FromStringAndSize already defined in libp3pystub.lib(p3pystub_pystub.obj)
pythonembed.lib(stringobject.obj) : error LNK2005: _PyString_FromString already defined in libp3pystub.lib(p3pystub_pystub.obj)
pythonembed.lib(stringobject.obj) : error LNK2005: _PyString_FromFormat already defined in libp3pystub.lib(p3pystub_pystub.obj)
pythonembed.lib(stringobject.obj) : error LNK2005: _PyString_Size already defined in libp3pystub.lib(p3pystub_pystub.obj)
pythonembed.lib(stringobject.obj) : error LNK2005: _PyString_AsString already defined in libp3pystub.lib(p3pystub_pystub.obj)
pythonembed.lib(stringobject.obj) : error LNK2005: _PyString_AsStringAndSize already defined in libp3pystub.lib(p3pystub_pystub.obj)
pythonembed.lib(stringobject.obj) : error LNK2005: _PyString_InternInPlace already defined in libp3pystub.lib(p3pystub_pystub.obj)
pythonembed.lib(stringobject.obj) : error LNK2005: _PyString_InternFromString already defined in libp3pystub.lib(p3pystub_pystub.obj)
pythonembed.lib(errors.obj) : error LNK2005: _PyErr_Restore already defined in libp3pystub.lib(p3pystub_pystub.obj)
pythonembed.lib(errors.obj) : error LNK2005: _PyErr_SetString already defined in libp3pystub.lib(p3pystub_pystub.obj)
pythonembed.lib(errors.obj) : error LNK2005: _PyErr_Occurred already defined in libp3pystub.lib(p3pystub_pystub.obj)
pythonembed.lib(errors.obj) : error LNK2005: _PyErr_ExceptionMatches already defined in libp3pystub.lib(p3pystub_pystub.obj)
pythonembed.lib(errors.obj) : error LNK2005: _PyErr_Fetch already defined in libp3pystub.lib(p3pystub_pystub.obj)
pythonembed.lib(errors.obj) : error LNK2005: _PyErr_Clear already defined in libp3pystub.lib(p3pystub_pystub.obj)
pythonembed.lib(errors.obj) : error LNK2005: _PyErr_NoMemory already defined in libp3pystub.lib(p3pystub_pystub.obj)
pythonembed.lib(errors.obj) : error LNK2005: _PyErr_Format already defined in libp3pystub.lib(p3pystub_pystub.obj)
pythonembed.lib(abstract.obj) : error LNK2005: _PyObject_Cmp already defined in libp3pystub.lib(p3pystub_pystub.obj)
pythonembed.lib(abstract.obj) : error LNK2005: _PyObject_Type already defined in libp3pystub.lib(p3pystub_pystub.obj)
pythonembed.lib(abstract.obj) : error LNK2005: _PyObject_GetBuffer already defined in libp3pystub.lib(p3pystub_pystub.obj)
pythonembed.lib(abstract.obj) : error LNK2005: _PyBuffer_Release already defined in libp3pystub.lib(p3pystub_pystub.obj)
pythonembed.lib(abstract.obj) : error LNK2005: _PyNumber_Check already defined in libp3pystub.lib(p3pystub_pystub.obj)
pythonembed.lib(abstract.obj) : error LNK2005: _PyNumber_Int already defined in libp3pystub.lib(p3pystub_pystub.obj)
pythonembed.lib(abstract.obj) : error LNK2005: _PyNumber_Long already defined in libp3pystub.lib(p3pystub_pystub.obj)
pythonembed.lib(abstract.obj) : error LNK2005: _PyNumber_Float already defined in libp3pystub.lib(p3pystub_pystub.obj)
pythonembed.lib(abstract.obj) : error LNK2005: _PySequence_Check already defined in libp3pystub.lib(p3pystub_pystub.obj)
pythonembed.lib(abstract.obj) : error LNK2005: _PySequence_Size already defined in libp3pystub.lib(p3pystub_pystub.obj)
pythonembed.lib(abstract.obj) : error LNK2005: _PySequence_GetItem already defined in libp3pystub.lib(p3pystub_pystub.obj)
pythonembed.lib(abstract.obj) : error LNK2005: _PySequence_Tuple already defined in libp3pystub.lib(p3pystub_pystub.obj)
pythonembed.lib(abstract.obj) : error LNK2005: _PySequence_Fast already defined in libp3pystub.lib(p3pystub_pystub.obj)
pythonembed.lib(abstract.obj) : error LNK2005: _PyMapping_GetItemString already defined in libp3pystub.lib(p3pystub_pystub.obj)
pythonembed.lib(abstract.obj) : error LNK2005: _PyObject_CallObject already defined in libp3pystub.lib(p3pystub_pystub.obj)
pythonembed.lib(abstract.obj) : error LNK2005: _PyObject_Call already defined in libp3pystub.lib(p3pystub_pystub.obj)
pythonembed.lib(abstract.obj) : error LNK2005: _PyObject_CallFunction already defined in libp3pystub.lib(p3pystub_pystub.obj)
pythonembed.lib(abstract.obj) : error LNK2005: __PyObject_CallFunction_SizeT already defined in libp3pystub.lib(p3pystub_pystub.obj)
pythonembed.lib(abstract.obj) : error LNK2005: _PyObject_CallMethod already defined in libp3pystub.lib(p3pystub_pystub.obj)
pythonembed.lib(abstract.obj) : error LNK2005: __PyObject_CallMethod_SizeT already defined in libp3pystub.lib(p3pystub_pystub.obj)
pythonembed.lib(abstract.obj) : error LNK2005: _PyObject_CallMethodObjArgs already defined in libp3pystub.lib(p3pystub_pystub.obj)
pythonembed.lib(abstract.obj) : error LNK2005: _PyObject_CallFunctionObjArgs already defined in libp3pystub.lib(p3pystub_pystub.obj)
pythonembed.lib(abstract.obj) : error LNK2005: _PyObject_IsInstance already defined in libp3pystub.lib(p3pystub_pystub.obj)
pythonembed.lib(getargs.obj) : error LNK2005: _PyArg_Parse already defined in libp3pystub.lib(p3pystub_pystub.obj)
pythonembed.lib(getargs.obj) : error LNK2005: __PyArg_Parse_SizeT already defined in libp3pystub.lib(p3pystub_pystub.obj)
pythonembed.lib(getargs.obj) : error LNK2005: _PyArg_ParseTuple already defined in libp3pystub.lib(p3pystub_pystub.obj)
pythonembed.lib(getargs.obj) : error LNK2005: __PyArg_ParseTuple_SizeT already defined in libp3pystub.lib(p3pystub_pystub.obj)
pythonembed.lib(getargs.obj) : error LNK2005: _PyArg_ParseTupleAndKeywords already defined in libp3pystub.lib(p3pystub_pystub.obj)
pythonembed.lib(getargs.obj) : error LNK2005: __PyArg_ParseTupleAndKeywords_SizeT already defined in libp3pystub.lib(p3pystub_pystub.obj)
pythonembed.lib(getargs.obj) : error LNK2005: _PyArg_UnpackTuple already defined in libp3pystub.lib(p3pystub_pystub.obj)
pythonembed.lib(intobject.obj) : error LNK2005: _PyInt_Type already defined in libp3pystub.lib(p3pystub_pystub.obj)
pythonembed.lib(intobject.obj) : error LNK2005: _PyInt_FromLong already defined in libp3pystub.lib(p3pystub_pystub.obj)
pythonembed.lib(intobject.obj) : error LNK2005: _PyInt_FromSize_t already defined in libp3pystub.lib(p3pystub_pystub.obj)
pythonembed.lib(intobject.obj) : error LNK2005: _PyInt_AsLong already defined in libp3pystub.lib(p3pystub_pystub.obj)
pythonembed.lib(intobject.obj) : error LNK2005: _PyInt_AsSsize_t already defined in libp3pystub.lib(p3pystub_pystub.obj)
pythonembed.lib(pystate.obj) : error LNK2005: __PyThreadState_Current already defined in libp3pystub.lib(p3pystub_pystub.obj)
pythonembed.lib(pystate.obj) : error LNK2005: _PyThreadState_New already defined in libp3pystub.lib(p3pystub_pystub.obj)
pythonembed.lib(pystate.obj) : error LNK2005: _PyThreadState_Clear already defined in libp3pystub.lib(p3pystub_pystub.obj)
pythonembed.lib(pystate.obj) : error LNK2005: _PyThreadState_Delete already defined in libp3pystub.lib(p3pystub_pystub.obj)
pythonembed.lib(pystate.obj) : error LNK2005: _PyThreadState_Get already defined in libp3pystub.lib(p3pystub_pystub.obj)
pythonembed.lib(pystate.obj) : error LNK2005: _PyThreadState_Swap already defined in libp3pystub.lib(p3pystub_pystub.obj)
pythonembed.lib(pystate.obj) : error LNK2005: _PyGILState_Ensure already defined in libp3pystub.lib(p3pystub_pystub.obj)
pythonembed.lib(pystate.obj) : error LNK2005: _PyGILState_Release already defined in libp3pystub.lib(p3pystub_pystub.obj)
pythonembed.lib(longobject.obj) : error LNK2005: _PyLong_Type already defined in libp3pystub.lib(p3pystub_pystub.obj)
pythonembed.lib(longobject.obj) : error LNK2005: _PyLong_FromLong already defined in libp3pystub.lib(p3pystub_pystub.obj)
pythonembed.lib(longobject.obj) : error LNK2005: _PyLong_FromUnsignedLong already defined in libp3pystub.lib(p3pystub_pystub.obj)
pythonembed.lib(longobject.obj) : error LNK2005: _PyLong_AsLong already defined in libp3pystub.lib(p3pystub_pystub.obj)
pythonembed.lib(longobject.obj) : error LNK2005: _PyLong_AsSsize_t already defined in libp3pystub.lib(p3pystub_pystub.obj)
pythonembed.lib(longobject.obj) : error LNK2005: _PyLong_AsUnsignedLong already defined in libp3pystub.lib(p3pystub_pystub.obj)
pythonembed.lib(longobject.obj) : error LNK2005: _PyLong_FromLongLong already defined in libp3pystub.lib(p3pystub_pystub.obj)
pythonembed.lib(longobject.obj) : error LNK2005: _PyLong_FromUnsignedLongLong already defined in libp3pystub.lib(p3pystub_pystub.obj)
pythonembed.lib(longobject.obj) : error LNK2005: _PyLong_FromSize_t already defined in libp3pystub.lib(p3pystub_pystub.obj)
pythonembed.lib(longobject.obj) : error LNK2005: _PyLong_AsLongLong already defined in libp3pystub.lib(p3pystub_pystub.obj)
pythonembed.lib(longobject.obj) : error LNK2005: _PyLong_AsUnsignedLongLong already defined in libp3pystub.lib(p3pystub_pystub.obj)
pythonembed.lib(floatobject.obj) : error LNK2005: _PyFloat_Type already defined in libp3pystub.lib(p3pystub_pystub.obj)
pythonembed.lib(floatobject.obj) : error LNK2005: _PyFloat_FromDouble already defined in libp3pystub.lib(p3pystub_pystub.obj)
pythonembed.lib(floatobject.obj) : error LNK2005: _PyFloat_AsDouble already defined in libp3pystub.lib(p3pystub_pystub.obj)
pythonembed.lib(_warnings.obj) : error LNK2005: _PyErr_WarnEx already defined in libp3pystub.lib(p3pystub_pystub.obj)
pythonembed.lib(_warnings.obj) : error LNK2005: _PyErr_Warn already defined in libp3pystub.lib(p3pystub_pystub.obj)
pythonembed.lib(tupleobject.obj) : error LNK2005: _PyTuple_Type already defined in libp3pystub.lib(p3pystub_pystub.obj)
pythonembed.lib(tupleobject.obj) : error LNK2005: _PyTuple_New already defined in libp3pystub.lib(p3pystub_pystub.obj)
pythonembed.lib(tupleobject.obj) : error LNK2005: _PyTuple_Size already defined in libp3pystub.lib(p3pystub_pystub.obj)
pythonembed.lib(tupleobject.obj) : error LNK2005: _PyTuple_GetItem already defined in libp3pystub.lib(p3pystub_pystub.obj)
pythonembed.lib(tupleobject.obj) : error LNK2005: _PyTuple_Pack already defined in libp3pystub.lib(p3pystub_pystub.obj)
pythonembed.lib(methodobject.obj) : error LNK2005: _PyCFunction_NewEx already defined in libp3pystub.lib(p3pystub_pystub.obj)
pythonembed.lib(methodobject.obj) : error LNK2005: _PyCFunction_New already defined in libp3pystub.lib(p3pystub_pystub.obj)
pythonembed.lib(modsupport.obj) : error LNK2005: _Py_InitModule4TraceRefs already defined in libp3pystub.lib(p3pystub_pystub.obj)
pythonembed.lib(modsupport.obj) : error LNK2005: _Py_BuildValue already defined in libp3pystub.lib(p3pystub_pystub.obj)
pythonembed.lib(modsupport.obj) : error LNK2005: __Py_BuildValue_SizeT already defined in libp3pystub.lib(p3pystub_pystub.obj)
pythonembed.lib(modsupport.obj) : error LNK2005: _PyEval_CallFunction already defined in libp3pystub.lib(p3pystub_pystub.obj)
pythonembed.lib(modsupport.obj) : error LNK2005: _PyModule_AddObject already defined in libp3pystub.lib(p3pystub_pystub.obj)
pythonembed.lib(modsupport.obj) : error LNK2005: _PyModule_AddIntConstant already defined in libp3pystub.lib(p3pystub_pystub.obj)
pythonembed.lib(modsupport.obj) : error LNK2005: _PyModule_AddStringConstant already defined in libp3pystub.lib(p3pystub_pystub.obj)
pythonembed.lib(boolobject.obj) : error LNK2005: __Py_ZeroStruct already defined in libp3pystub.lib(p3pystub_pystub.obj)
pythonembed.lib(boolobject.obj) : error LNK2005: __Py_TrueStruct already defined in libp3pystub.lib(p3pystub_pystub.obj)
pythonembed.lib(boolobject.obj) : error LNK2005: _PyBool_FromLong already defined in libp3pystub.lib(p3pystub_pystub.obj)
pythonembed.lib(genobject.obj) : error LNK2005: _PyGen_Type already defined in libp3pystub.lib(p3pystub_pystub.obj)
pythonembed.lib(memoryobject.obj) : error LNK2005: _PyMemoryView_FromObject already defined in libp3pystub.lib(p3pystub_pystub.obj)
   Creating library built/empire.lib and object built/empire.exp
LINK : warning LNK4098: defaultlib 'MSVCRTD' conflicts with use of other libs; use /NODEFAULTLIB:library
empire.obj : error LNK2001: unresolved external symbol _initlibpandadna
empire.obj : error LNK2001: unresolved external symbol "void __cdecl init_libpandadna(void)" (?init_libpandadna@@YAXXZ)
built/empire.exe : fatal error LNK1120: 2 unresolved externals
The following command returned non-zero value (1120): link /LTCG /LTCG:STATUS /nologo /out:built/empire.exe "built/aes.obj" "built/empire.obj" "built/main...

**Comment by loblao** [comment]
Did you run postbuild after compiling Panda3D?

**Comment by DarthMDev** [comment]
@loblao  Linking...
   Creating library built/empire.lib and object built/empire.exp
LINK : warning LNK4098: defaultlib 'MSVCRTD' conflicts with use of other libs; use /NODEFAULTLIB:library
aes.obj : error LNK2001: unresolved external symbol _Py_InitModule4
main.obj : error LNK2001: unresolved external symbol _Py_InitModule4
empire.obj : error LNK2001: unresolved external symbol _initlibpandadna
empire.obj : error LNK2001: unresolved external symbol "void __cdecl init_libpandadna(void)" (?init_libpandadna@@YAXXZ)
ode.lib(p3interrogatedb_composite2.obj) : error LNK2001: unresolved external symbol __imp__Py_InitModule4
interrogatedb.lib(interrogatedb_pydtool.obj) : error LNK2001: unresolved external symbol __imp__Py_InitModule4
built/empire.exe : fatal error LNK1120: 4 unresolved externals
The following command returned non-zero value (1120): link /LTCG /LTCG:STATUS /nologo /out:built/empire.exe "built/aes.obj" "built/empire.obj" "built/main...

**Comment by loblao** [comment]
You're trying to link `void init_libpandadna(void)` but the linker cannot find it. Have you added the correct libs?
