### ISSUE TITLE
The system cannot find the file specified.

### ISSUE THREAD

**Issue by ghost** [nirai-compiler/src#7]
Hi. I'm using Nirai to compile my Toontown server (Aren't there enough already?) and it gives me an error when making CXX nodes.
Here's the traceback:
http://pastebin.com/LTREQuT4
It doesn't show what file it cannot find, so it has gotten me beat,
Thank you :D

**Comment by loblao** [comment]
It cannot find the compiler. Are you on Windows?

**Comment by ghost** [comment]
Yes, I am on Windows 10. Is this supported?

**Comment by loblao** [comment]
Use a [VS2010 command prompt](http://stackoverflow.com/questions/7190419/where-can-i-find-the-visual-studio-2010-command-prompt-executable) to invoke make.py.

**Comment by ghost** [comment]
This problem was solved, but now I have another. I'll close this and make a new issue for the sake of organization.
