### ISSUE TITLE
Cannot open include file: 'openssl/conf.h': No file or directory.

### ISSUE THREAD

**Issue by ghost** [nirai-compiler/src#8]
Hi, I'm trying to compile my Toontown server, and I am (now) getting this error:
`C:\ttrbRECODE2\build>C:\Panda3D-1.9.0\python\ppython.exe make.py -c
Warning: pandac.PandaModules is deprecated, import from panda3d.core instead
Compiling CXX codes...
aes.cxx
C:\ttrbRECODE2\build\nirai\src\aes.cxx(3) : fatal error C1083: Cannot open include file: 'openssl/conf.h': No such file or directory
The following command returned non-zero value (2): cl /c /GF /MP4 /DPy_BUILD_CORE /DNTDDI_VERSION=0x0501 /wd4996 /wd4275 /wd4267 /wd4101 /wd4273 /nolog...`
So I went and got the openssl stuff from their github and errors started spewing out and I thought "This can't be the one for Nirai!". What are Nirai's prerequisites?

**Comment by mfwass** [comment]
Install OpenSSL.

It'd likely be easier to not build OpenSSL yourself, if I were you I'd download the latest precompiled binaries.

**Comment by ghost** [comment]
Where do I get the precompiled binaries? I found this [here](http://www.npcglib.org/~stathis/blog/precompiled-openssl/) but I don't know if this is one you would recommend. Also, how would I install them?

**Comment by mfwass** [comment]
Grab the latest stable for VS2010, if you have any issues @loblao may be able to recommend a specific version.

I'm able to compile TLOPO's Nirai perfectly fine on mac with the latest build.

**Comment by lolman8776** [comment]
Where from?

**Comment by lolman8776** [comment]
How do I install it? Run the exe?

**Comment by ghost** [comment]
How do I install it so the Visual Studio 2010 CMD prompt recognizes it?
